version: '3.6'
services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOCKER_BUILDKIT=1
    restart: always
    ports:
      - 1972
      - 55038:52773
      - 53773
      - 55030:5000
    volumes:
      - ./:/home/irisowner/dev
