version: '3.6'
services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOCKER_BUILDKIT=1
    restart: always
    ports:
      # IRIS native
      - 0.0.0.0:1972:1972
      # IRIS web http://localhost:52773/csp/sys/UtilHome.csp
      - 0.0.0.0:52773:52773
      # IRIS Recorder helper http://localhost:5000
      - 0.0.0.0:5000:5000
    volumes:
      - ./:/home/irisowner/dev
