name: Cloud Run Deploy

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/build-default.yaml@master
    with:
      # Replace the name: parameter below to have your application deployed at
      # https://project-name.demo.community.intersystems.com/
      name: iris-recorder-helper
      port: 5000
    secrets:
      # Do not forget to add Secret in GitHub Repoository Settings with name SERVICE_ACCOUNT_KEY
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}